version: "3.9"

services:
  go-app:
    build:
      context: ./go-app
    container_name: go_app_8391
    expose:
      - "8391"
    networks:
      - lis-server_app_net
    restart: unless-stopped

networks:
  lis-server_app_net:
    external: true
